# Generated by Django 5.2.8 on 2025-11-13 02:54

import logistics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=logistics.models.generate_tracking_number, max_length=50, unique=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('fee_required', models.BooleanField(default=True)),
                ('fees', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, default=80.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='In Transit', max_length=50)),
                ('origin', models.CharField(default='New York, NY', max_length=200)),
                ('destination', models.CharField(default='Los Angeles, CA', max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
